 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coffe.management.system;

import java.awt.Cursor;
import javax.swing.JOptionPane; 
import model.user;


/**
 *
 * @author Mehdi KHATTABI
 */
public class Home extends javax.swing.JFrame {
    public String status;
     public String name;
    

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    public Home(String userStatus , String userName) {
        initComponents();
        System.out.print("status"+userStatus);
        System.out.print("name"+userName);
        status = userStatus;
        name = userName;
        if(!status.equals("admin"))
        {
            lblCategory.setVisible(false);
            lblProduct.setVisible(false);
            lblEdit.setVisible(false);
            lblVerify.setVisible(false);
            lblWaiter.setVisible(false);
            lblViewBill.setVisible(false);
            lblGood.setVisible(true);
            jLabel1.setVisible(false);
            //int id = Integer.parseInt(lblId.getText());
            jLabel3.setVisible(true);
            lblName1.setText(name);
        }
        else if(!status.equals("waiter")){
            lblCategory.setVisible(true);
            lblProduct.setVisible(true);
            lblEdit.setVisible(true);
            lblVerify.setVisible(true);
            lblWaiter.setVisible(true);
            lblViewBill.setVisible(true);
            jLabel1.setVisible(true);
            lblName1.setVisible(false);
            jLabel3.setVisible(false);
            lblGood.setVisible(false);
            lblName.getName();
            lblName.setText(name);
            
        }
            
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPlaceOrder = new javax.swing.JLabel();
        lblViewBill = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        lblVerify = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();
        lblWaiter = new javax.swing.JLabel();
        lblGood = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitMouseMoved(evt);
            }
        });
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1050, 40, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, -1, 290));

        lblPlaceOrder.setFont(new java.awt.Font("Segoe UI Variable", 1, 23)); // NOI18N
        lblPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        lblPlaceOrder.setText("Place Order");
        lblPlaceOrder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblPlaceOrderMouseMoved(evt);
            }
        });
        lblPlaceOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPlaceOrderMousePressed(evt);
            }
        });
        getContentPane().add(lblPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 770, 210, 70));

        lblViewBill.setFont(new java.awt.Font("Segoe UI Variable", 1, 23)); // NOI18N
        lblViewBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View Bills & Order Placed Details.png"))); // NOI18N
        lblViewBill.setText("Details");
        lblViewBill.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblViewBillMouseMoved(evt);
            }
        });
        lblViewBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblViewBillMousePressed(evt);
            }
        });
        getContentPane().add(lblViewBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 130, 90));

        lblCategory.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/categ.png"))); // NOI18N
        lblCategory.setText("Manage Category");
        lblCategory.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCategoryMouseMoved(evt);
            }
        });
        lblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCategoryMousePressed(evt);
            }
        });
        getContentPane().add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 270, 80));

        lblLogout.setFont(new java.awt.Font("Segoe UI Variable", 1, 23)); // NOI18N
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        lblLogout.setText("Log Out");
        lblLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblLogoutMouseMoved(evt);
            }
        });
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLogoutMousePressed(evt);
            }
        });
        getContentPane().add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 930, 180, 60));

        lblProduct.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        lblProduct.setForeground(new java.awt.Color(255, 255, 255));
        lblProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        lblProduct.setText("New Product");
        lblProduct.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblProductMouseMoved(evt);
            }
        });
        lblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblProductMousePressed(evt);
            }
        });
        getContentPane().add(lblProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 210, 80));

        lblVerify.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        lblVerify.setForeground(new java.awt.Color(255, 255, 255));
        lblVerify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify users.png"))); // NOI18N
        lblVerify.setText("Verify User");
        lblVerify.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblVerifyMouseMoved(evt);
            }
        });
        lblVerify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVerifyMousePressed(evt);
            }
        });
        getContentPane().add(lblVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 20, 190, 80));

        lblEdit.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        lblEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        lblEdit.setText("View, Edit & Delete Product");
        lblEdit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblEditMouseMoved(evt);
            }
        });
        lblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEditMousePressed(evt);
            }
        });
        getContentPane().add(lblEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 370, 80));

        lblWaiter.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        lblWaiter.setForeground(new java.awt.Color(255, 255, 255));
        lblWaiter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nouveau-symbole-rouge2.png"))); // NOI18N
        lblWaiter.setText("Add User");
        lblWaiter.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblWaiterMouseMoved(evt);
            }
        });
        lblWaiter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblWaiterMousePressed(evt);
            }
        });
        getContentPane().add(lblWaiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 20, 180, 80));

        lblGood.setFont(new java.awt.Font("Poor Richard", 2, 55)); // NOI18N
        lblGood.setForeground(new java.awt.Color(255, 255, 255));
        lblGood.setText("GOOD   FOOD   IS   GOOD   MOOD");
        getContentPane().add(lblGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 800, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel1.setText("Welcome ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 210, 80));

        lblName.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 160, 80));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel3.setText("Welcome ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 210, 100));

        lblName1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        lblName1.setText("mehdi");
        getContentPane().add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 160, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InterfaceBack.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseMoved
        // TODO add your handling code here:
         exit.setCursor( Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));    
    }//GEN-LAST:event_exitMouseMoved

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to exit ?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0){
        System.exit(0);
        } 
    }//GEN-LAST:event_exitMousePressed

    private void lblPlaceOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlaceOrderMousePressed
        // TODO add your handling code here:
        new PlaceOrder(name).setVisible(true);
    }//GEN-LAST:event_lblPlaceOrderMousePressed

    private void lblPlaceOrderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlaceOrderMouseMoved
        // TODO add your handling code here:
        lblPlaceOrder.setCursor( Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblPlaceOrderMouseMoved

    private void lblCategoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCategoryMousePressed
        // TODO add your handling code here:
        new ManageCategory().setVisible(true);
    }//GEN-LAST:event_lblCategoryMousePressed

    private void lblCategoryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCategoryMouseMoved
        // TODO add your handling code here:
        lblCategory.setCursor( Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblCategoryMouseMoved

    private void lblProductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductMousePressed
        // TODO add your handling code here:
        new NewProduct().setVisible(true);
    }//GEN-LAST:event_lblProductMousePressed

    private void lblProductMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductMouseMoved
        // TODO add your handling code here:
        lblProduct.setCursor( Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblProductMouseMoved

    private void lblEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMousePressed
        // TODO add your handling code here:
        new EditProduct().setVisible(true);
    }//GEN-LAST:event_lblEditMousePressed

    private void lblEditMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseMoved
        // TODO add your handling code here:
        lblEdit.setCursor( Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblEditMouseMoved

    private void lblWaiterMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWaiterMouseMoved
        // TODO add your handling code here:
        lblWaiter.setCursor( Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblWaiterMouseMoved

    private void lblWaiterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWaiterMousePressed
        // TODO add your handling code here:
        
        new signup().setVisible(true);
    }//GEN-LAST:event_lblWaiterMousePressed

    private void lblLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMousePressed
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(null, "Do you really want to LogOut","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_lblLogoutMousePressed

    private void lblLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseMoved
        // TODO add your handling code here:
        lblLogout.setCursor( Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblLogoutMouseMoved

    private void lblViewBillMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewBillMouseMoved
        // TODO add your handling code here:
        lblViewBill.setCursor( Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblViewBillMouseMoved

    private void lblVerifyMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerifyMouseMoved
        // TODO add your handling code here:
        lblVerify.setCursor( Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblVerifyMouseMoved

    private void lblVerifyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerifyMousePressed
        // TODO add your handling code here:
        new VerifyUser().setVisible(true);
    }//GEN-LAST:event_lblVerifyMousePressed

    private void lblViewBillMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewBillMousePressed
        // TODO add your handling code here:
        new Details(name,status).setVisible(true);
    }//GEN-LAST:event_lblViewBillMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblGood;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblPlaceOrder;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblVerify;
    private javax.swing.JLabel lblViewBill;
    private javax.swing.JLabel lblWaiter;
    // End of variables declaration//GEN-END:variables
}
