package coffe.management.system;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import dao.BillDao;
import dao.CategoryDao;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;
import dao.ProductDao;
import java.awt.Cursor;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Bill;
import model.Category;
import model.Product;
import model.user;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Mehdi KHATTABI
 */
public class PlaceOrder extends javax.swing.JFrame {

    public int billId = 1;
    public int subTotal = 0;
    public int productPrice = 0;
    public int productTotal = 0;
    public String waiterName;

    public PlaceOrder() {
        initComponents();
        btnClear.setEnabled(false);
        btnAdd.setEnabled(false);
        btnBill.setEnabled(false);
        
    }

    /**
     * Creates new form PlaceOrder
     *
     * @param userName
     */
    
    public PlaceOrder(String userName) {
        initComponents();
        
        JFormattedTextField tf = ((JSpinner.DefaultEditor) spnQuantity.getEditor()).getTextField();
        tf.setEnabled(false);
        waiterName = userName;
        lblWaiter.setText(userName);
        if (!lblProduct.getText().equals("")&& !lblPrice.getText().equals("")&&!lblTotal.getText().equals(""))
            btnAdd.setEnabled(true);
        else
            btnAdd.setEnabled(false);
    }

    public void clear() {
        lblProduct.setText("");
        lblPrice.setText("");
        lblTotal.setText("");
        
        spnQuantity.setValue(0);
        
        
    }

    public void getAllRecordsByCategory(String category) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list = ProductDao.getAllRecordsByCategory(category);
        Iterator<Product> itr = list.iterator();
        while (itr.hasNext()) {
            Product productobj = itr.next();
            dtm.addRow(new Object[]{productobj.getName()});
        }
    }

    public void filterProductByName(String name, String category) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list = ProductDao.filterProductByName(name, category);
        Iterator<Product> itr = list.iterator();
        while (itr.hasNext()) {
            Product productobj = itr.next();
            dtm.addRow(new Object[]{productobj.getName()});
        }
    }

    /*public void getAllRecordsByWaiter(String waiter) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<Bill> list = BillDao.getAllRecordsByWaiter(waiter);
        Iterator<Bill> itr = list.iterator();
        while (itr.hasNext()) {
            Bill billObj = itr.next();
            dtm.addRow(new Object[]{billObj.getName()});
        }
    }*/

    public void clearProductFilds() {
        lblProduct.setText("");
        lblPrice.setText("");
        spnQuantity.setValue(0);
        lblTotal.setText("");
        lblSub.setText("");
    }

    public void validateFields() {

    }

    //private void formComponentShown (java.awt.event. ComponentEvent evt){
    // TODO add your handling code here:
    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        spnQuantity = new javax.swing.JSpinner();
        lblSub = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBill = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblWaiter = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 200));
        setMaximumSize(new java.awt.Dimension(1154, 688));
        setMinimumSize(new java.awt.Dimension(1154, 688));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1154, 688));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel2.setText("Bill N° :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 60, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel3.setText("Waiter :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 70, -1));

        lblId.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 80, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/categ.png"))); // NOI18N
        jLabel5.setText("Category :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 160, -1));

        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 250, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 250, 340));

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel6.setText("Product :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 80, -1));

        lblProduct.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        getContentPane().add(lblProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 160, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel8.setText("Quantity :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 80, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel10.setText("Price : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 60, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel9.setText("SubTotal :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, 80, 30));

        lblPrice.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 80, 40));

        spnQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQuantityStateChanged(evt);
            }
        });
        getContentPane().add(spnQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 82, 30));

        lblSub.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        getContentPane().add(lblSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 630, 70, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel15.setText("Total :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 240, 60, 30));

        lblTotal.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 240, 50, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, -1, 190));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, 10, 200));

        btnAdd.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nouveau-symbole-rouge2.png"))); // NOI18N
        btnAdd.setText("Add Order");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 170, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 140, 40));

        btnBill.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        btnBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        btnBill.setText("      Bill");
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 630, 140, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 250, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jLabel17.setText("Search");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jLabel18.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel18MouseMoved(evt);
            }
        });
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18MousePressed(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 30, 40));

        jLabel19.setFont(new java.awt.Font("Sitka Text", 1, 48)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        jLabel19.setText("Place Order");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel4.setText("DH");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, -1, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel7.setText("DH");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 240, 30, 30));

        lblWaiter.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        getContentPane().add(lblWaiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 120, 80));

        jLabel11.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel11.setText("DH");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, -1, 50));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 450, 200));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, 170, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/psd.png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name = lblProduct.getText();
        String price = lblPrice.getText();
        String quantity = String.valueOf(spnQuantity.getValue());
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.addRow(new Object[]{name, price, quantity, productTotal});
        subTotal = subTotal + productTotal;
        lblSub.setText(String.valueOf(subTotal));
        btnBill.setEnabled(true);
        clear();
        //validateField () ;

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
        // TODO add your handling code here:
        
        String waiter = lblWaiter.getText () ;
        
        
        String productName = lblProduct.getText();
        String quantity = String.valueOf(spnQuantity.getValue());
        String price = lblPrice.getText();
        System.out.println("-------" + price);
        String total = lblSub.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-M-yyyy hh:mm:ss");
        Date date = new Date();

        String todaydate = sdf.format(date);
        //String total = String.valueOf(subTotal);
        Bill bill = new Bill();
        bill.setName(productName);
        bill.setQuanity(quantity);
        bill.setPrice(price);
        bill.setId(billId);
        bill.setWaiter(waiter);
        bill.setDate(todaydate);
        bill.setTotal(total);
        BillDao.save(bill);

// Création du document PDF
        String path = "C:\\Users\\Mehdi KHATTABI\\Desktop\\Bills\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + billId + ".pdf"));
            doc.open();

            Paragraph cafeName = new Paragraph("                                                        MMA RESTAURANT                                                   ");
            Paragraph cafeName2 = new Paragraph("                                                            05.32.36.52.48                                                   ");
            doc.add(cafeName);
            doc.add(cafeName2);
            Paragraph starLine = new Paragraph("***************************************************************************************************************");
            doc.add(starLine);
            //Paragraph paragraph4 = new Paragraph("Product: " + productName + "\n\t Pu : " + price + "   *   " +quantity);
            Paragraph paragraph3 = new Paragraph("Bill N°: " + lblId.getText() + "\nWaiter: " + waiter + "\n");
            //doc.add(paragraph4);

            PdfPTable table = new PdfPTable(4);
            table.addCell("           Name");
            // table.addCell("Date");
            table.addCell("          Price");
            table.addCell("         Quantity");
            table.addCell("          Total");

            for (int i = 0; i < jTable2.getRowCount(); i++) {
                String name = jTable2.getValueAt(i, 0).toString();
                // String date = jTable2.getValueAt(i, 1).toString();
                String pric = jTable2.getValueAt(i, 1).toString();
                String quantit = jTable2.getValueAt(i, 2).toString();
                String totalValue = jTable2.getValueAt(i, 3).toString();

                table.addCell(name);
                // table.addCell(date);
                table.addCell("             "+pric);
                table.addCell("             "+quantit);
                table.addCell("             "+totalValue);
            }

            doc.add(table);
            Paragraph subTotal = new Paragraph("        \t Total: " + total + " DH \n");
            doc.add(subTotal);
            doc.add(starLine);
            doc.add(paragraph3);
            
           

            Paragraph today = new Paragraph("Date: " + todaydate + "\n");
            doc.add(today);

            doc.add(starLine);

            Paragraph thanksMsg = new Paragraph("                                                        Thank You For Your Visit                                                   ");
            doc.add(thanksMsg);

            doc.close();
            clear();
            setVisible(false);
            new PlaceOrder().setVisible(true);
            OpenPdf.openById(String.valueOf(billId));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            doc.close();
            
        }


    }//GEN-LAST:event_btnBillActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jLabel18MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseMoved
        // TODO add your handling code here:
        jLabel18.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel18MouseMoved

    private void jLabel18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MousePressed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel18MousePressed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String name = txtSearch.getText();
        String category = (String) cmbCategory.getSelectedItem();
        filterProductByName(name, category);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:{
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String productName = model.getValueAt(index, 0).toString();
        Product product = ProductDao.getProductByName(productName);
        lblProduct.setText(product.getName());
        lblPrice.setText(product.getPrice());
        spnQuantity.setValue(1);
        lblTotal.setText(product.getPrice());
        productPrice = Integer.parseInt(product.getPrice());
        productTotal = Integer.parseInt(product.getPrice());
        btnAdd.setEnabled(true);
        btnClear.setEnabled(true);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
        String category = (String) cmbCategory.getSelectedItem();
        getAllRecordsByCategory(category);

    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        billId = Integer.parseInt(BillDao.getId());
        lblId.setText(BillDao.getId());
        ArrayList<Category> list = CategoryDao.getAllRecords();
        Iterator<Category> itr = list.iterator();
        while (itr.hasNext()) {
            Category categoryObj = itr.next();
            cmbCategory.addItem(categoryObj.getName());
            String category = (String) cmbCategory.getSelectedItem();
            getAllRecordsByCategory(category);
        }
    }//GEN-LAST:event_formComponentShown

    private void spnQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQuantityStateChanged
        // TODO add your handling code here:
        int quantity = (Integer) spnQuantity.getValue();
        if (quantity <= 1) {
            spnQuantity.setValue(1);
            quantity = 1;
        }
        productTotal = productPrice * quantity;
        lblTotal.setText(String.valueOf(productTotal));
    }//GEN-LAST:event_spnQuantityStateChanged

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblWaiter;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
